from pydantic import BaseModel, Field
from typing import Literal

# Define the structured output for all Specialist Agents (Alpha, Beta, Gamma)
class SpecialistRecommendation(BaseModel):
    """A single, prioritized recommendation from a specialist agent."""
    
    agent_name: Literal["Architect", "Alchemist", "Trainer"] = Field(
        description="The name of the specialist providing the advice."
    )
    priority_level: Literal["CRITICAL", "HIGH", "MEDIUM", "LOW"] = Field(
        description="The urgency of the recommendation. CRITICAL for safety (e.g., vascular risk), HIGH for immediate need (e.g., poor sleep)."
    )
    instruction: str = Field(
        description="A clear, single-sentence actionable instruction for the user."
    )
    rationale: str = Field(
        description="A concise scientific justification based on the agent's domain expertise (e.g., Glymphatic Clearance, Gut-Brain Axis)."
    )
    domain_category: str = Field(
        description="The scientific domain this covers (e.g., 'Sleep & Vascular', 'Nutrition & Stress', 'Cognitive Training')."
    )

# Define the final consolidated plan output by the Prime Concierge
class ConsolidatedPlan(BaseModel):
    """The final, merged, and prioritized plan generated by the Prime Concierge."""
    executive_summary: str = Field(
        description="A 2-3 sentence overview of the day's primary focus and risk management theme."
    )
    prioritized_actions: list[SpecialistRecommendation] = Field(
        description="The final list of merged and prioritized recommendations, ordered from CRITICAL to LOW."
    )